package br.ufes.weatherdatadisplay.view;

import javax.swing.JComboBox;
import javax.swing.JLabel;


/**
 *
 * @author pedroh
 */
public class DadosMediosTempoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTempoView
     */
    public DadosMediosTempoView() {
        initComponents();
        setVisible(true);
        setLocation(280, 15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTemperatura = new javax.swing.JLabel();
        lbHumidade = new javax.swing.JLabel();
        lbPressao = new javax.swing.JLabel();
        lbdTemperatura = new javax.swing.JLabel();
        lbdHumidade = new javax.swing.JLabel();
        lbdPressao = new javax.swing.JLabel();
        lbPeriodo = new javax.swing.JLabel();
        cbPeriodo = new javax.swing.JComboBox<>();
        lbRegistros = new javax.swing.JLabel();
        lbdRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dados Médios");

        lbTemperatura.setText("Temperatura:");

        lbHumidade.setText("Humidade:");

        lbPressao.setText("Pressão:");

        lbPeriodo.setText("Período:");

        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diário", "Semanal", "Mensal" }));

        lbRegistros.setText("Registros:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTemperatura)
                    .addComponent(lbHumidade)
                    .addComponent(lbPressao)
                    .addComponent(lbPeriodo)
                    .addComponent(lbRegistros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbdTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdHumidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdPressao, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(cbPeriodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPeriodo)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperatura)
                    .addComponent(lbdTemperatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHumidade)
                    .addComponent(lbdHumidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPressao)
                    .addComponent(lbdPressao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRegistros)
                    .addComponent(lbdRegistros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel lbHumidade;
    private javax.swing.JLabel lbPeriodo;
    private javax.swing.JLabel lbPressao;
    private javax.swing.JLabel lbRegistros;
    private javax.swing.JLabel lbTemperatura;
    private javax.swing.JLabel lbdHumidade;
    private javax.swing.JLabel lbdPressao;
    private javax.swing.JLabel lbdRegistros;
    private javax.swing.JLabel lbdTemperatura;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbPeriodo() {
        return cbPeriodo;
    }

    public JLabel getLbdHumidade() {
        return lbdHumidade;
    }

    public JLabel getLbdPressao() {
        return lbdPressao;
    }

    public JLabel getLbdRegistros() {
        return lbdRegistros;
    }

    public JLabel getLbdTemperatura() {
        return lbdTemperatura;
    }

}
