/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.weatherdatadisplay.view;

/**
 *
 * @author pedroh
 */
public class PrincipalView extends javax.swing.JFrame {

    private final CadastroTempoView cadastroTempoView;
    private final UltimaAtualizacaoTempoView ultimaAtualizacaoTempoView;
    private final DadosMediosTempoView dadosMediosView;
    private final RegistroView registroView;
    private final ConfiguracaoDoSistemaView configuracaoDoSistemaView;
    
    
    public PrincipalView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
        
        cadastroTempoView = new CadastroTempoView();
        this.add(cadastroTempoView);
        this.cadastroTempoView.setLocation(15, 15);
        
        
        ultimaAtualizacaoTempoView = new UltimaAtualizacaoTempoView();
        this.add(ultimaAtualizacaoTempoView);
        this.ultimaAtualizacaoTempoView.setLocation(15, 250);
        
        dadosMediosView = new DadosMediosTempoView();
        this.add(dadosMediosView);
        this.dadosMediosView.setLocation(280, 15);
        
        
        registroView = new RegistroView();
        this.add(registroView);
        this.registroView.setLocation(280, 205);
        
        configuracaoDoSistemaView = new ConfiguracaoDoSistemaView();
        this.add(configuracaoDoSistemaView);
        this.configuracaoDoSistemaView.setLocation(523, 15);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Data Display");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
