/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.weatherdatadisplay.view;

import javax.swing.JLabel;


/**
 *
 * @author pedroh
 */
public class UltimaAtualizacaoTempoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTempoView
     */
    public UltimaAtualizacaoTempoView() {
        initComponents();
        setVisible(true);
        setLocation(15, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbData = new javax.swing.JLabel();
        lbTemperatura = new javax.swing.JLabel();
        lbHumidade = new javax.swing.JLabel();
        lbPressao = new javax.swing.JLabel();
        lbdData = new javax.swing.JLabel();
        lbdTemperatura = new javax.swing.JLabel();
        lbdHumidade = new javax.swing.JLabel();
        lbdPressao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Última Atualização");

        lbData.setText("Data:");

        lbTemperatura.setText("Temperatura:");

        lbHumidade.setText("Humidade:");

        lbPressao.setText("Pressão:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbData)
                    .addComponent(lbTemperatura)
                    .addComponent(lbHumidade)
                    .addComponent(lbPressao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbdData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdHumidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdPressao, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbData)
                    .addComponent(lbdData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperatura)
                    .addComponent(lbdTemperatura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHumidade)
                    .addComponent(lbdHumidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPressao)
                    .addComponent(lbdPressao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHumidade;
    private javax.swing.JLabel lbPressao;
    private javax.swing.JLabel lbTemperatura;
    private javax.swing.JLabel lbdData;
    private javax.swing.JLabel lbdHumidade;
    private javax.swing.JLabel lbdPressao;
    private javax.swing.JLabel lbdTemperatura;
    // End of variables declaration//GEN-END:variables

    public JLabel getLbdData() {
        return lbdData;
    }

    public JLabel getLbdHumidade() {
        return lbdHumidade;
    }

    public JLabel getLbdPressao() {
        return lbdPressao;
    }

    public JLabel getLbdTemperatura() {
        return lbdTemperatura;
    }

}
